apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-demo-sa
  namespace: platform-lab
  labels:
    app: nginx-demo
    app.kubernetes.io/part-of: platform-lab
automountServiceAccountToken: false