apiVersion: v1
kind: ServiceAccount
metadata:
  name: java-demo-sa
  namespace: platform-lab
  labels:
    app: java-demo
    app.kubernetes.io/name: java-demo
    app.kubernetes.io/part-of: platform-lab
automountServiceAccountToken: false