apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo
  namespace: platform-lab
  labels:
    app: java-demo
    app.kubernetes.io/name: java-demo
    app.kubernetes.io/part-of: platform-lab
spec:
  replicas: 3
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app: java-demo

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  template:
    metadata:
      labels:
        app: java-demo
        app.kubernetes.io/name: java-demo
        app.kubernetes.io/part-of: platform-lab

    spec:
      serviceAccountName: java-demo-sa
      automountServiceAccountToken: false

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: java-demo
          image: platform-lab-java:1.0.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8081
              protocol: TCP

          envFrom:
            - configMapRef:
                name: java-demo-config

            - secretRef:
                name: java-demo-secret

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL