apiVersion: v1
kind: Secret
metadata:
  name: nginx-demo-secret
  namespace: platform-lab
  labels:
    app: nginx-demo
type: Opaque
stringData:
  DEMO_USERNAME: platform-user
  DEMO_PASSWORD: local-password-not-for-production